# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rwp_rcpp <- function(X, B) {
    .Call('_robsel_rwp_rcpp', PACKAGE = 'robsel', X, B)
}

